/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedManagerSettingsRouteImport } from './routes/_authed/manager/settings'
import { Route as AuthedManagerSecurityRouteImport } from './routes/_authed/manager/security'
import { Route as AuthedManagerMembersRouteImport } from './routes/_authed/manager/members'
import { Route as AuthedManagerHouseholdsRouteImport } from './routes/_authed/manager/households'
import { Route as AuthedManagerDashboardRouteImport } from './routes/_authed/manager/dashboard'
import { Route as AuthedHubTreeRouteImport } from './routes/_authed/hub/tree'
import { Route as AuthedHubRelationshipsRouteImport } from './routes/_authed/hub/relationships'
import { Route as AuthedHubMembersRouteImport } from './routes/_authed/hub/members'
import { Route as AuthedHubGiftsRouteImport } from './routes/_authed/hub/gifts'
import { Route as AuthedHubEventsRouteImport } from './routes/_authed/hub/events'
import { Route as AuthedHubDashboardRouteImport } from './routes/_authed/hub/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedManagerSettingsRoute = AuthedManagerSettingsRouteImport.update({
  id: '/manager/settings',
  path: '/manager/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedManagerSecurityRoute = AuthedManagerSecurityRouteImport.update({
  id: '/manager/security',
  path: '/manager/security',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedManagerMembersRoute = AuthedManagerMembersRouteImport.update({
  id: '/manager/members',
  path: '/manager/members',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedManagerHouseholdsRoute = AuthedManagerHouseholdsRouteImport.update({
  id: '/manager/households',
  path: '/manager/households',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedManagerDashboardRoute = AuthedManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHubTreeRoute = AuthedHubTreeRouteImport.update({
  id: '/hub/tree',
  path: '/hub/tree',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHubRelationshipsRoute = AuthedHubRelationshipsRouteImport.update({
  id: '/hub/relationships',
  path: '/hub/relationships',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHubMembersRoute = AuthedHubMembersRouteImport.update({
  id: '/hub/members',
  path: '/hub/members',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHubGiftsRoute = AuthedHubGiftsRouteImport.update({
  id: '/hub/gifts',
  path: '/hub/gifts',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHubEventsRoute = AuthedHubEventsRouteImport.update({
  id: '/hub/events',
  path: '/hub/events',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHubDashboardRoute = AuthedHubDashboardRouteImport.update({
  id: '/hub/dashboard',
  path: '/hub/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/hub/dashboard': typeof AuthedHubDashboardRoute
  '/hub/events': typeof AuthedHubEventsRoute
  '/hub/gifts': typeof AuthedHubGiftsRoute
  '/hub/members': typeof AuthedHubMembersRoute
  '/hub/relationships': typeof AuthedHubRelationshipsRoute
  '/hub/tree': typeof AuthedHubTreeRoute
  '/manager/dashboard': typeof AuthedManagerDashboardRoute
  '/manager/households': typeof AuthedManagerHouseholdsRoute
  '/manager/members': typeof AuthedManagerMembersRoute
  '/manager/security': typeof AuthedManagerSecurityRoute
  '/manager/settings': typeof AuthedManagerSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/hub/dashboard': typeof AuthedHubDashboardRoute
  '/hub/events': typeof AuthedHubEventsRoute
  '/hub/gifts': typeof AuthedHubGiftsRoute
  '/hub/members': typeof AuthedHubMembersRoute
  '/hub/relationships': typeof AuthedHubRelationshipsRoute
  '/hub/tree': typeof AuthedHubTreeRoute
  '/manager/dashboard': typeof AuthedManagerDashboardRoute
  '/manager/households': typeof AuthedManagerHouseholdsRoute
  '/manager/members': typeof AuthedManagerMembersRoute
  '/manager/security': typeof AuthedManagerSecurityRoute
  '/manager/settings': typeof AuthedManagerSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/hub/dashboard': typeof AuthedHubDashboardRoute
  '/_authed/hub/events': typeof AuthedHubEventsRoute
  '/_authed/hub/gifts': typeof AuthedHubGiftsRoute
  '/_authed/hub/members': typeof AuthedHubMembersRoute
  '/_authed/hub/relationships': typeof AuthedHubRelationshipsRoute
  '/_authed/hub/tree': typeof AuthedHubTreeRoute
  '/_authed/manager/dashboard': typeof AuthedManagerDashboardRoute
  '/_authed/manager/households': typeof AuthedManagerHouseholdsRoute
  '/_authed/manager/members': typeof AuthedManagerMembersRoute
  '/_authed/manager/security': typeof AuthedManagerSecurityRoute
  '/_authed/manager/settings': typeof AuthedManagerSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/hub/dashboard'
    | '/hub/events'
    | '/hub/gifts'
    | '/hub/members'
    | '/hub/relationships'
    | '/hub/tree'
    | '/manager/dashboard'
    | '/manager/households'
    | '/manager/members'
    | '/manager/security'
    | '/manager/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/hub/dashboard'
    | '/hub/events'
    | '/hub/gifts'
    | '/hub/members'
    | '/hub/relationships'
    | '/hub/tree'
    | '/manager/dashboard'
    | '/manager/households'
    | '/manager/members'
    | '/manager/security'
    | '/manager/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/hub/dashboard'
    | '/_authed/hub/events'
    | '/_authed/hub/gifts'
    | '/_authed/hub/members'
    | '/_authed/hub/relationships'
    | '/_authed/hub/tree'
    | '/_authed/manager/dashboard'
    | '/_authed/manager/households'
    | '/_authed/manager/members'
    | '/_authed/manager/security'
    | '/_authed/manager/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/manager/settings': {
      id: '/_authed/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof AuthedManagerSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/manager/security': {
      id: '/_authed/manager/security'
      path: '/manager/security'
      fullPath: '/manager/security'
      preLoaderRoute: typeof AuthedManagerSecurityRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/manager/members': {
      id: '/_authed/manager/members'
      path: '/manager/members'
      fullPath: '/manager/members'
      preLoaderRoute: typeof AuthedManagerMembersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/manager/households': {
      id: '/_authed/manager/households'
      path: '/manager/households'
      fullPath: '/manager/households'
      preLoaderRoute: typeof AuthedManagerHouseholdsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/manager/dashboard': {
      id: '/_authed/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AuthedManagerDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/hub/tree': {
      id: '/_authed/hub/tree'
      path: '/hub/tree'
      fullPath: '/hub/tree'
      preLoaderRoute: typeof AuthedHubTreeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/hub/relationships': {
      id: '/_authed/hub/relationships'
      path: '/hub/relationships'
      fullPath: '/hub/relationships'
      preLoaderRoute: typeof AuthedHubRelationshipsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/hub/members': {
      id: '/_authed/hub/members'
      path: '/hub/members'
      fullPath: '/hub/members'
      preLoaderRoute: typeof AuthedHubMembersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/hub/gifts': {
      id: '/_authed/hub/gifts'
      path: '/hub/gifts'
      fullPath: '/hub/gifts'
      preLoaderRoute: typeof AuthedHubGiftsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/hub/events': {
      id: '/_authed/hub/events'
      path: '/hub/events'
      fullPath: '/hub/events'
      preLoaderRoute: typeof AuthedHubEventsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/hub/dashboard': {
      id: '/_authed/hub/dashboard'
      path: '/hub/dashboard'
      fullPath: '/hub/dashboard'
      preLoaderRoute: typeof AuthedHubDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedHubDashboardRoute: typeof AuthedHubDashboardRoute
  AuthedHubEventsRoute: typeof AuthedHubEventsRoute
  AuthedHubGiftsRoute: typeof AuthedHubGiftsRoute
  AuthedHubMembersRoute: typeof AuthedHubMembersRoute
  AuthedHubRelationshipsRoute: typeof AuthedHubRelationshipsRoute
  AuthedHubTreeRoute: typeof AuthedHubTreeRoute
  AuthedManagerDashboardRoute: typeof AuthedManagerDashboardRoute
  AuthedManagerHouseholdsRoute: typeof AuthedManagerHouseholdsRoute
  AuthedManagerMembersRoute: typeof AuthedManagerMembersRoute
  AuthedManagerSecurityRoute: typeof AuthedManagerSecurityRoute
  AuthedManagerSettingsRoute: typeof AuthedManagerSettingsRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedHubDashboardRoute: AuthedHubDashboardRoute,
  AuthedHubEventsRoute: AuthedHubEventsRoute,
  AuthedHubGiftsRoute: AuthedHubGiftsRoute,
  AuthedHubMembersRoute: AuthedHubMembersRoute,
  AuthedHubRelationshipsRoute: AuthedHubRelationshipsRoute,
  AuthedHubTreeRoute: AuthedHubTreeRoute,
  AuthedManagerDashboardRoute: AuthedManagerDashboardRoute,
  AuthedManagerHouseholdsRoute: AuthedManagerHouseholdsRoute,
  AuthedManagerMembersRoute: AuthedManagerMembersRoute,
  AuthedManagerSecurityRoute: AuthedManagerSecurityRoute,
  AuthedManagerSettingsRoute: AuthedManagerSettingsRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
